---
- name: Deploy and update
  hosts: inventario
  
  tasks:
    - name: Crear directorio para playbooks si no existe
      file:
        path: "{{ ansible_env.HOME }}/CRUD-RUST-DOCKER"
        state: directory
        mode: '0755'  # Permisos para el directorio
    - name: Clonar repositorio
      git:
        repo: https://github.com/kelok3rik/CRUD-RUST-DOCKER.git
        dest: "{{ ansible_env.HOME }}/CRUD-RUST-DOCKER"
        force: yes
        update: yes
        
    - name: Detener el contenedor Docker existente
      # command: docker-compose down
      # args:
      #   chdir: "{{ ansible_env.HOME }}/CRUD-RUST-DOCKER"
      shell: |
          cd "{{ ansible_env.HOME }}/CRUD-RUST-DOCKER/crud"
          docker-compose down

   # - name: Eliminar el contenedor Docker existente
   #   command: docker-compose rm -f
   #   args:
   #     chdir: "{{ ansible_env.HOME }}/CRUD-RUST-DOCKER"
   #   ignore_errors: true

    - name: Construir el contenedor Docker
      #command: docker build -t crud:latest .
      shell: |
          cd "{{ ansible_env.HOME }}/CRUD-RUST-DOCKER/crud"
          docker-compose build
      

    - name: Iniciar el contenedor Docker
      shell: |
          cd "{{ ansible_env.HOME }}/CRUD-RUST-DOCKER/crud"
          docker-compose up -d
        
