- name: Deploy and update
  hosts: inventario
  
  tasks:
    - name: Clonar repositorio
      git:
        repo: https://github.com/kelok3rik/CRUD-RUST-DOCKER.git
        dest: /home/kelok3rik/CRUD-RUST-DOCKER

    - name: Construir e iniciar el contenedor Docker
      shell: |
        cd /home/kelok3rik/CRUD-RUST-DOCKER
        docker build . -t crud:latest && cd docker && docker compose up -d
        
    
       
