- name: Deploy and update
  hosts: inventario
  
  tasks:
<<<<<<< HEAD
    - name: Detener el contenedor Docker existente
      shell: |
        cd /home/kelok3rik/CRUD-RUST-DOCKER/crud/docker
        docker-compose down
     

    - name: Eliminar el contenedor Docker existente
      shell: |
        cd /home/kelok3rik/CRUD-RUST-DOCKER/crud/docker
        docker-compose rm -f
    

    - name: Clonar repositorio
      git:
        repo: https://github.com/kelok3rik/CRUD-RUST-DOCKER.git
        dest: /home/kelok3rik/CRUD-RUST-DOCKER


    - name: Construir el contenedor Docker
      shell: |
        cd /home/kelok3rik/CRUD-RUST-DOCKER/crud
        docker build -t crud:latest .
    - name: Iniciar el contenedor Docker
      shell: |
        cd /home/kelok3rik/CRUD-RUST-DOCKER/crud/docker
        docker-compose down
        docker-compose up -d
        docker-compose up -d
=======
    - name: Crear directorio para playbooks si no existe
      file:
        path: "{{ ansible_env.HOME }}/CRUD-RUST-DOCKER"
        state: directory
        mode: '0755'  # Permisos para el directorio
    - name: Clonar repositorio
      git:
        repo: https://github.com/kelok3rik/CRUD-RUST-DOCKER.git
        dest: "{{ ansible_env.HOME }}/CRUD-RUST-DOCKER"
        force: yes
        update: yes
        
    - name: Detener el contenedor Docker existente
      # command: docker-compose down
      # args:
      #   chdir: "{{ ansible_env.HOME }}/CRUD-RUST-DOCKER"
      shell: |
          cd /root/CRUD-RUST-DOCKER/docker
          docker-compose down

    - name: Eliminar el contenedor Docker existente
      shell: |
          cd /root/CRUD-RUST-DOCKER/docker
          docker-compose rm -f
      ignore_errors: true
     
    - name: Construir el contenedor Docker
      #command: docker build -t crud:latest .
      shell: |
          cd /root/CRUD-RUST-DOCKER/
          docker build -t crud:latest .
      

    - name: Iniciar el contenedor Docker
      shell: |
          cd /root/CRUD-RUST-DOCKER/docker
          docker-compose up -d
        
>>>>>>> 367aa2697fc6c64897bdfd73afe43528734f0608
