- name: Deploy and update
  hosts: inventario
  
  tasks:
    - name: Clonar repositorio
      git:
        repo: https://github.com/kelok3rik/CRUD-RUST-DOCKER.git
        dest: /home/kelok3rik/CRUD-RUST-DOCKER

    - name: Construir el contenedor Docker
      shell: |
        cd /home/kelok3rik/CRUD-RUST-DOCKER
        docker build -t crud:latest .
        
    - name: Iniciar el contenedor Docker
      shell: |
        cd /home/kelok3rik/CRUD-RUST-DOCKER/docker
        docker-compose up -d
       
