- name: Deploy and update
  hosts: inventario
  
  tasks:
    - name: Detener el contenedor Docker existente
      shell: |
        cd /CRUD-RUST-DOCKER/crud/docker
        docker-compose down
     

    - name: Eliminar el contenedor Docker existente
      shell: |
        cd /CRUD-RUST-DOCKER/crud/docker
        docker-compose rm -f
    

    - name: Clonar repositorio
      git:
        repo: https://github.com/kelok3rik/CRUD-RUST-DOCKER.git
        dest: /home/kelok3rik/CRUD-RUST-DOCKER


    - name: Construir el contenedor Docker
      shell: |
        cd /CRUD-RUST-DOCKER/crud
        docker build -t crud:latest .
    - name: Iniciar el contenedor Docker
      shell: |
        cd /CRUD-RUST-DOCKER/crud/docker
        docker-compose down
        docker-compose up -d
        docker-compose up -d
